-- THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT
--WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
--LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
--FOR A PARTICULAR PURPOSE.


CREATE FUNCTION [dbo].[GetDBBackupState]
(
	@dbint_id int
)
RETURNS bit
AS
BEGIN
	DECLARE @result bit = 0
	select top 1 @result = 1 from sys.dm_exec_requests 
	where command like 'BACKUP DATABASE%' and database_id = @dbint_id
	RETURN @result
END
